"""One-off data fix: clear the GHS 0.00 invoices and the suspensions they caused.

Background
----------
`POST /platform/operators` created operators with `billing_status='active'` and
never set `monthly_fee_ghs`, so it defaulted to 0.00.  `generate_monthly_invoices`
then issued GHS 0.00 invoices, which Paystack cannot charge and the operator
therefore cannot pay.  Each one ran through the grace period and `enforce_billing`
suspended the operator — blocking captive-portal sales (503) and admin writes (403).

This script repairs the operators that bug already damaged.  The bug itself is
fixed separately: the create endpoint and form now require a fee, and
`generate_monthly_invoices` skips zero-fee operators.

What it does, in one transaction
--------------------------------
1. Waives every unpaid GHS 0.00 invoice (status `issued`/`overdue` -> `waived`),
   writing a `waived` billing event for each.  Waived, not deleted, so the audit
   trail records that these were a bug rather than real receivables.
2. For each operator that owned one of those invoices AND is currently suspended:
   restores `status='approved'`, resets `billing_status` to `active`, sets the fee,
   and writes a `reactivated` billing event.

`billing_status` matters: `PUT /operators/{id}/status` does not reset it, and
`generate_monthly_invoices` only selects `billing_status == 'active'`.  Left at
`past_due`, an operator would silently never be invoiced again.

Safety
------
* Dry run by default.  Nothing is written without `--apply`.
* Scoped by predicate to unpaid *zero-amount* invoices, so it cannot touch a real
  receivable, and to operators that are *currently suspended* and own one.
* Idempotent: a second run matches nothing and reports no work.
* Single transaction — all of it lands or none of it does.

Usage
-----
    docker exec hotspot-backend python -m src.db.fixes.phase0_zero_fee_invoices --fee 0
    docker exec hotspot-backend python -m src.db.fixes.phase0_zero_fee_invoices --fee 0 --apply
"""
from __future__ import annotations

import argparse
import asyncio
import os
import sys
from decimal import Decimal

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.db.base import async_session_factory
from src.db.models import ISPOperator, OperatorBillingEvent, OperatorInvoice

WAIVE_REASON = "GHS 0.00 invoice generated by the operator-creation bug (fee never set)."


async def _matched_invoices(db: AsyncSession) -> list[OperatorInvoice]:
    """Unpaid zero-amount invoices — by construction, only this bug's output."""
    return list(
        (
            await db.execute(
                select(OperatorInvoice)
                .where(
                    OperatorInvoice.amount_ghs == 0,
                    OperatorInvoice.status.in_(["issued", "overdue"]),
                )
                .order_by(OperatorInvoice.invoice_number)
            )
        )
        .scalars()
        .all()
    )


async def run(fee: Decimal, apply: bool) -> int:
    async with async_session_factory() as db:
        invoices = await _matched_invoices(db)

        if not invoices:
            print("No unpaid GHS 0.00 invoices found — nothing to do.")
            return 0

        operator_ids = {inv.isp_operator_id for inv in invoices}
        operators = list(
            (
                await db.execute(
                    select(ISPOperator).where(ISPOperator.id.in_(operator_ids)).order_by(ISPOperator.name)
                )
            )
            .scalars()
            .all()
        )
        by_id = {op.id: op for op in operators}

        # Only operators the billing job actually knocked over. An operator
        # suspended for another reason must not be reactivated by a billing fix.
        to_reactivate = [op for op in operators if op.status == "suspended"]
        not_suspended = [op for op in operators if op.status != "suspended"]

        print(f"\n{'APPLYING' if apply else 'DRY RUN — no writes'}\n")

        print(f"Invoices to waive ({len(invoices)}):")
        for inv in invoices:
            op = by_id.get(inv.isp_operator_id)
            print(f"  {inv.invoice_number}  {op.name if op else inv.isp_operator_id:<14}  "
                  f"GHS {inv.amount_ghs}  {inv.status} -> waived")

        print(f"\nOperators to reactivate ({len(to_reactivate)}):")
        for op in to_reactivate:
            print(f"  {op.name} ({op.slug})")
            print(f"      status:         {op.status} -> approved")
            print(f"      billing_status: {op.billing_status} -> active")
            print(f"      monthly_fee:    GHS {op.monthly_fee_ghs} -> GHS {fee}")
        for op in not_suspended:
            print(f"  {op.name} ({op.slug}) — not suspended, left alone "
                  f"(status={op.status}, billing_status={op.billing_status})")

        if not apply:
            print("\nRe-run with --apply to commit.")
            return 0

        for inv in invoices:
            inv.status = "waived"
            db.add(
                OperatorBillingEvent(
                    isp_operator_id=inv.isp_operator_id,
                    event_type="waived",
                    description=f"Invoice {inv.invoice_number} waived by platform owner.",
                    event_metadata={
                        "invoice_id": str(inv.id),
                        "invoice_number": inv.invoice_number,
                        "amount_ghs": str(inv.amount_ghs),
                        "reason": WAIVE_REASON,
                        "waived_by": "phase0_zero_fee_invoices",
                    },
                )
            )

        for op in to_reactivate:
            # Only this operator's invoices — a global list would over-report on
            # the reactivation event of every operator in the batch.
            waived_numbers = [
                inv.invoice_number for inv in invoices if inv.isp_operator_id == op.id
            ]
            op.status = "approved"
            op.billing_status = "active"
            op.monthly_fee_ghs = fee
            db.add(
                OperatorBillingEvent(
                    isp_operator_id=op.id,
                    event_type="reactivated",
                    description=(
                        f"{op.name} reactivated after waiving zero-amount invoices "
                        f"({', '.join(n for n in waived_numbers)})."
                    ),
                    event_metadata={
                        "reason": WAIVE_REASON,
                        "monthly_fee_ghs": str(fee),
                        "reactivated_by": "phase0_zero_fee_invoices",
                    },
                )
            )

        await db.commit()
        print(f"\n✅ Committed: {len(invoices)} invoice(s) waived, "
              f"{len(to_reactivate)} operator(s) reactivated at GHS {fee}/month.")
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--fee",
        type=Decimal,
        required=True,
        help="monthly_fee_ghs to set on every reactivated operator (0 = comped; "
             "the invoice job skips zero-fee operators)",
    )
    parser.add_argument("--apply", action="store_true", help="commit; without it this is a dry run")
    args = parser.parse_args()
    if args.fee < 0:
        parser.error("--fee cannot be negative")
    return asyncio.run(run(args.fee, args.apply))


if __name__ == "__main__":
    raise SystemExit(main())
